Add Grid Product subcommand man page
hyperledger/grid-docs pull request #136
Opened 2020-10-05 17:14 UTC by dnewh

Signed-off-by: Davey Newhall <newhall@bitwise.io>

2020-10-05 21:12 UTC, chenette submitted a review, later dismissed

2020-10-05 21:12 UTC, chenette commented on docs/0.1/references/cli/grid-product.1.md
> +ENVIRONMENT VARIABLES
A "mid-level" command like this should list the subcommands after the options.  See splinter-circuit.1.md for an example of a mid-level command:

https://github.com/Cargill/splinter-docs/blob/master/docs/0.4/references/cli/splinter-circuit.1.md
https://www.splinter.dev/docs/0.4/references/cli/splinter-circuit.1.html

2020-10-05 21:15 UTC, chenette requested changes

2020-10-05 21:15 UTC, chenette commented on docs/0.1/references/cli/grid-product.1.md
> +ENVIRONMENT VARIABLES
A "mid-level" command like this should list the subcommands after the options. See splinter-circuit.1.md for an example of a mid-level command:

https://github.com/Cargill/splinter-docs/blob/master/docs/0.4/references/cli/splinter-circuit.1.md
https://www.splinter.dev/docs/0.4/references/cli/splinter-circuit.1.html

2020-10-05 21:25 UTC, chenette approved these changes

2020-10-07 16:28 UTC, dplumb94 approved these changes

2020-10-08 19:36 UTC, merged