Add grid product smart contract specification
hyperledger/grid-docs pull request #153
Opened 2020-10-16 19:16 UTC by RyanLassigBanks

Signed-off-by: Ryan Banks <rbanks@bitwise.io>

2020-10-22 17:26 UTC, dplumb94 requested changes

2020-10-22 17:26 UTC, dplumb94 commented on docs/0.1/grid_product_smart_contract_specification.md
> +Therefore, all addresses starting with:
I think this sentence is incomplete. Maybe something like "Therefore, addresses with starting with the following string are Grid products"

2020-11-10 17:30 UTC, dplumb94 approved these changes

2020-11-10 17:30 UTC, dnewh requested changes

2020-11-10 17:30 UTC, dnewh commented on docs/0.1/grid_product_smart_contract_specification.md
> +* Address of the Organization the Product is being deleted for Address of the
I think there is a line break and a bullet point missing here

2020-11-10 17:35 UTC, dnewh approved these changes

2020-11-10 17:35 UTC, vaporos approved these changes

2020-11-10 17:37 UTC, dplumb94 approved these changes

2020-11-10 17:51 UTC, merged