Add Grid on Sawtooth procedure
hyperledger/grid-docs pull request #158
Opened 2020-10-22 17:07 UTC by dnewh

This adds the "Running Grid on Sawtooth" procedure. This is similar to the "Running Grid on Splinter" procedure but omits mention of circuits as that is not a feature of Sawtooth.

2020-11-04 17:16 UTC, dplumb94 requested changes

2020-11-06 15:45 UTC, dnewh commented on docs/0.1/grid_on_sawtooth.md
> +The example Sawtooth docker-compose file creates a network with three nodes
updated

2020-11-06 15:45 UTC, dnewh commented on docs/0.1/grid_on_sawtooth.md
> +This environment includes the Pike, Product, and Schema smart contracts.
updated

2020-11-10 18:58 UTC, RyanLassigBanks approved these changes

2020-11-12 18:57 UTC, dplumb94 approved these changes

2020-11-12 19:04 UTC, merged