Add compose file for running grid-docs website
hyperledger/grid-docs pull request #159
Opened 2020-10-26 20:10 UTC by rbuysse

Signed-off-by: Ryan Beck-Buysse <rbuysse@bitwise.io>

2020-11-10 17:10 UTC, RyanLassigBanks approved these changes

2020-11-12 18:57 UTC, dplumb94 requested changes
Can you add the info thats in the commit description as a comment on this file? I don't know if its clear what the purpose of this file is without it. Also add license header if possible.

2020-11-17 20:06 UTC, dplumb94 approved these changes

2020-11-18 20:28 UTC, dnewh approved these changes

2020-11-18 22:50 UTC, merged