Add Grid 0.1 release documentation
hyperledger/grid-docs pull request #175
Opened 2020-11-18 21:22 UTC by dplumb94

Adds content to the downloads and release pages

2020-12-21 21:37 UTC, dnewh submitted a review, later dismissed

2021-01-18 18:48 UTC, rbuysse submitted a review, later dismissed

2021-01-20 18:33 UTC, vaporos requested changes

2021-01-20 18:33 UTC, vaporos commented on releases/0.1/index.md
> +release, see the [Grid release notes](https://github.com/hyperledger/grid/blob/master/RELEASE_NOTES.md).
This link isn't valid.

2021-01-25 20:34 UTC, dnewh submitted a review, later dismissed

2021-01-25 20:58 UTC, dnewh approved these changes

2021-02-03 20:04 UTC, vaporos approved these changes

2021-02-03 20:05 UTC, merged