Add update spec for Pike 2
hyperledger/grid-docs pull request #207
Opened 2021-03-29 18:57 UTC by dnewh

This updates the Pike smart contract specification document for the Pike
2.0 update. This updates info about addressing, protos, and actions.

Signed-off-by: Davey Newhall <newhall@bitwise.io>

2021-03-31 20:05 UTC, dplumb94 requested changes
Would be nice to include what inputs are invalid, as well as inputs and output addresses for each transaction

2021-03-31 21:26 UTC, dnewh commented
> Would be nice to include what inputs are invalid, as well as inputs and output addresses for each transaction

These are included at line ~280

2021-04-05 15:55 UTC, dplumb94 approved these changes

2021-04-05 18:10 UTC, RyanLassigBanks approved these changes

2021-04-05 18:29 UTC, merged