Update How-tos for Pike 2
hyperledger/grid-docs pull request #208
Opened 2021-03-31 16:19 UTC by dnewh

This updates the how-to docs to work with Pike 2.0. This includes
updating yaml files to include owners, updating endpoints, and using
updated commands for organizations, agents, and roles.

Signed-off-by: Davey Newhall <newhall@bitwise.io>

2021-03-31 20:23 UTC, dplumb94 approved these changes

2021-03-31 20:23 UTC, dplumb94 commented on docs/0.2/creating_organizations.md
> +1. Request the list of roless.
typo

2021-03-31 20:26 UTC, dplumb94 requested changes
Typo in one of the steps. Also it might be nice to use something else to differentiate the Pike ID vs the name. maybe the ID could be "myorg" and the name "MyOrganization" or something

2021-03-31 20:28 UTC, dplumb94 commented
We also need a How To procedure for Pike specifically since there is some more complex functionality now. I would recommend writing one based on the example from the RFC which hits on all of the features. Also would be good to include how to use the alternate ID index to fetch orgs by alternate ID.

2021-04-02 19:24 UTC, dnewh commented on docs/0.2/creating_organizations.md
> +1. Request the list of roless.
fixed

2021-04-05 18:12 UTC, RyanLassigBanks submitted a review, later dismissed

2021-04-05 19:49 UTC, dplumb94 approved these changes

2021-04-05 20:02 UTC, RyanLassigBanks approved these changes

2021-04-06 03:09 UTC, merged