Add Product Sapling to planning
hyperledger/grid-docs pull request #215
Opened 2021-04-30 16:32 UTC by dnewh

This adds a brief page about the Product Sapling to the planned features
section. This includes a couple of the preliminary wireframes.

Signed-off-by: Davey Newhall <newhall@bitwise.io>

2021-04-30 17:35 UTC, RyanLassigBanks requested changes

2021-04-30 17:35 UTC, RyanLassigBanks commented on community/planning/product_sapling.md
> +repository includes the UI for Grid functionality. This document shows some
s/grid repository repository/grid repository

2021-05-03 16:39 UTC, dnewh commented on community/planning/product_sapling.md
> +repository includes the UI for Grid functionality. This document shows some
updated

2021-06-03 18:20 UTC, RyanLassigBanks approved these changes

2021-06-07 20:30 UTC, dplumb94 approved these changes
Looks good

2021-06-07 20:44 UTC, shannynalayna approved these changes
Tested

2021-06-07 20:46 UTC, merged