Add delegation example diagrams
hyperledger/grid-docs pull request #223
Opened 2021-05-25 21:22 UTC by dplumb94

- Adds a link to the delegation example from the feature page for more high-level info
- Replaces the condensed example with the full example from the RFC
- Adds diagrams for each step of the example

2021-05-27 16:38 UTC, dnewh requested changes

2021-05-27 16:38 UTC, dnewh commented on docs/0.2/using_pike.md
> +`tankops::can-decommission` permission and add `delta.TankOperator` as a super role.
This line should wrap at 80 characters

2021-05-27 16:38 UTC, dnewh commented on docs/0.2/using_pike.md
> +- `tankops::can-drive` allows agents to submit a transaction to update the `is_driving`
This line should wrap at 80 characters

2021-05-27 20:07 UTC, dplumb94 commented on docs/0.2/using_pike.md
> +`tankops::can-decommission` permission and add `delta.TankOperator` as a super role.
fixed

2021-05-27 20:07 UTC, dplumb94 commented on docs/0.2/using_pike.md
> +- `tankops::can-drive` allows agents to submit a transaction to update the `is_driving`
fixed

2021-05-27 21:06 UTC, dnewh approved these changes

2021-05-28 17:46 UTC, agunde406 approved these changes

2021-06-03 13:38 UTC, merged