update join_the_discussion.md
hyperledger/grid-docs pull request #229
Opened 2021-06-08 00:12 UTC by fishnexj

Signed-off-by: Jack Vishneski <fishnexj@gmail.com>

2021-06-08 12:56 UTC, agunde406 requested changes

2021-06-08 12:56 UTC, agunde406 commented on community/join_the_discussion.md
> +also hosts events for key milestones, with invites through our chatroom and mailing list.
Please wrap the lines at 80 characters so the build can pass the lint check.

2021-06-12 20:49 UTC, fishnexj commented
@agunde406 and @vaporos will you two please review changes, approve, and merge? The Grid website still advertises a recurring monthly community meeting we are no longer holding.

2021-06-23 17:34 UTC, vaporos approved these changes

2021-06-23 17:36 UTC, agunde406 approved these changes

2021-06-23 17:49 UTC, merged