Update addressing reference for Pike v2
hyperledger/grid-docs pull request #235
Opened 2021-06-22 20:17 UTC by dplumb94

Updates the Pike prefix and adds the role object prefix

Signed-off-by: Darian Plumb <dplumb@bitwise.io>

2021-06-25 16:43 UTC, peterschwarz approved these changes

2021-06-28 16:42 UTC, dnewh requested changes

2021-06-28 16:42 UTC, dnewh commented on docs/0.2/references/addressing_reference.md
> +      Roles: <code>02</code>
Should probably include the alternate ID prefix here "03"

2021-06-28 16:49 UTC, dnewh approved these changes

2021-07-07 19:53 UTC, shannynalayna approved these changes

2021-07-07 20:29 UTC, merged