Add clarification to Creating Locations
hyperledger/grid-docs pull request #271
Opened 2021-11-05 15:17 UTC by CLEckhardt

2021-11-05 16:13 UTC, dnewh requested changes

2021-11-05 16:13 UTC, dnewh commented on docs/0.1/creating_locations.md
> +3. Set `GRID_DAEMON_ENDPOINT` to the Grid daemon's endpoint (URL and port),
using all "1"s here was intentional. This is automatic numbering so it requires fewer changes for any further updates to the doc.

If you want to start at a specific number you use the notation `{:start="5"}` and have the first number be `5` followed by `1`s

2021-11-08 18:00 UTC, vaporos approved these changes

2021-11-12 14:28 UTC, shannynalayna approved these changes

2021-11-12 16:11 UTC, dnewh approved these changes

2021-11-12 20:08 UTC, merged