Add implementation details for "Future REST API"
hyperledger/grid-docs pull request #320
Opened 2022-02-22 17:07 UTC by shannynalayna

This change adds implementation details for the future Grid REST API to
the community planning section of the site.

Signed-off-by: Shannyn Telander <telander@bitwise.io>

2022-05-09 21:22 UTC, dnewh requested changes

2022-05-09 21:22 UTC, dnewh commented on community/planning/rest_api/index.md
> +`PUT / locations/{location_id}`. An example of the Rust API for this endpoint
extra space between the first `/` and `locations`

2022-05-09 21:35 UTC, CLEckhardt commented on community/planning/rest_api/index.md
> +Griddle has two primary functions, signing and proxying requests to the Grid
, should be :

2022-05-09 21:39 UTC, CLEckhardt commented on community/planning/rest_api/index.md
> +the batch. An `event_id` may be set for a batch and can be used
`data_change_id`

2022-05-09 22:10 UTC, CLEckhardt approved these changes

2022-07-20 15:27 UTC, shannynalayna commented
As our approach has shifted slightly, I will be closing this PR in favor of one to add more up-to-date information on our plan moving forward with the Grid REST API.

2022-07-20 15:27 UTC, closed without merging