Add research doc for one-round parallel queuer
hyperledger/grid-docs pull request #331
Opened 2022-04-12 19:20 UTC by CLEckhardt

Adds a doc to community/planning that examines the feasibility and practicality of one-round parallel queuing strategies.

2022-07-20 17:21 UTC, shannynalayna commented on community/planning/queuer_strat_one_round_parallel.md
> +througput of a queuing strategy while maintaining a batch submission order
sp/througput/throughput

2022-07-20 17:21 UTC, shannynalayna commented on community/planning/queuer_strat_one_round_parallel.md
> +average througput of a strategy at this point in Grid's development, we will
Same sp as above

2022-07-20 17:40 UTC, ameliabradley requested changes
Should there be a link to this new document?

2022-07-20 18:43 UTC, CLEckhardt commented on community/planning/queuer_strat_one_round_parallel.md
> +througput of a queuing strategy while maintaining a batch submission order
fixed, thanks!

2022-07-20 18:43 UTC, CLEckhardt commented on community/planning/queuer_strat_one_round_parallel.md
> +average througput of a strategy at this point in Grid's development, we will
fixed, thanks!

2022-07-20 18:59 UTC, ameliabradley approved these changes

2022-07-22 16:01 UTC, shannynalayna approved these changes

2022-07-22 16:23 UTC, merged